### PR TITLE
Linux release build

### LINKED ISSUE #11: Find a linux contributor
I don't have a machine running linux, but I would love to release Partyshare for it. I need someone running linux who would be willing to help with:

1. Add linux to the build target #7 
2. Test the target to make sure everything works, fixing any bugs
3. Make it publicly downloadable #9

### PR DESCRIPTION
**Pull request by hexagon6**
Fixes #11 :sweat_smile:

### CODE REVIEW

**Comment by hexagon6** [comment]
Can confirm this build works on Linux.

I setup an automated pipeline on my fork as an example: 
- CI builds: https://travis-ci.org/hexagon6/Partyshare 
- working branch: https://github.com/hexagon6/Partyshare/tree/ci/automated-unices-builds
- release builds: https://github.com/hexagon6/Partyshare/releases/tag/build-test2

@bhstahl contact me if you need support setting this up for BusterLabs.

**Comment by bhstahl** [comment]
Thanks for this @hexagon6! It's great to have your help here. For what it's worth, according to Google Analytics, clicks on the linux build link at https://partysha.re far outweigh any other platform. I can't wait to release it. 

Two notes before proceeding:

- #43 should negate the need for https://github.com/BusterLabs/Partyshare/pull/41/commits/337098511a4a2c882e26a7cf5c88b28718adeed5
- #44 should negate the need for https://github.com/BusterLabs/Partyshare/pull/41/commits/5101254c3bf41b2f4adc370606ae47b72394c8a0

Would you mind merging master, dropping those commits and see if the linux build works? 

Then, I'd love to merge #42 and draft a release which including the linux build 🍾 .

**Comment by hexagon6** [comment]
I incorporated your changes in master (7 commits) and my CI-pipeline built the package: 
https://github.com/hexagon6/Partyshare/releases/tag/partyshare-ci-build2

I reset those commits you requested and just added the `.travis.yml` for the CI-setup: https://github.com/BusterLabs/Partyshare/pull/47

**Comment by hexagon6** [comment]
forgot to pull again. I'll open a new PR for it

**Pull request closed without merging**
